# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 't130_leaf_flutter' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for t130_leaf_flutter
  flutter_application_path = 'flutter'
  eval(File.read(File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')), binding)
end
