// Autogenerated from Pigeon (v0.1.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
#import "Api.h"
#import <Flutter/Flutter.h>

#if !__has_feature(objc_arc)
#error File requires ARC to be enabled.
#endif

static NSDictionary* wrapResult(NSDictionary *result, FlutterError *error) {
  NSDictionary *errorDict = (NSDictionary *)[NSNull null];
  if (error) {
    errorDict = [NSDictionary dictionaryWithObjectsAndKeys:
        (error.code ? error.code : [NSNull null]), @"code",
        (error.message ? error.message : [NSNull null]), @"message",
        (error.details ? error.details : [NSNull null]), @"details",
        nil];
  }
  return [NSDictionary dictionaryWithObjectsAndKeys:
      (result ? result : [NSNull null]), @"result",
      errorDict, @"error",
      nil];
}

@interface Uint8List ()
+(Uint8List*)fromMap:(NSDictionary*)dict;
-(NSDictionary*)toMap;
@end
@interface String ()
+(String*)fromMap:(NSDictionary*)dict;
-(NSDictionary*)toMap;
@end

@implementation Uint8List
+(Uint8List*)fromMap:(NSDictionary*)dict {
  Uint8List* result = [[Uint8List alloc] init];
  result.bytesPerElement = dict[@"bytesPerElement"];
  if ((NSNull *)result.bytesPerElement == [NSNull null]) {
    result.bytesPerElement = nil;
  }
  return result;
}
-(NSDictionary*)toMap {
  return [NSDictionary dictionaryWithObjectsAndKeys:(self.bytesPerElement ? self.bytesPerElement : [NSNull null]), @"bytesPerElement", nil];
}
@end

@implementation String
+(String*)fromMap:(NSDictionary*)dict {
  String* result = [[String alloc] init];
  return result;
}
-(NSDictionary*)toMap {
  return [NSDictionary dictionaryWithObjectsAndKeys:nil];
}
@end

void HostImageApiSetup(id<FlutterBinaryMessenger> binaryMessenger, id<HostImageApi> api) {
  {
    FlutterBasicMessageChannel *channel =
      [FlutterBasicMessageChannel
        messageChannelWithName:@"dev.flutter.pigeon.HostImageApi.getSystemImageData"
        binaryMessenger:binaryMessenger];
    if (api) {
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        FlutterError *error;
        String *input = [String fromMap:message];
        Uint8List *output = [api getSystemImageData:input error:&error];
        callback(wrapResult([output toMap], error));
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
}
