// Autogenerated from Pigeon (v0.1.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
#import <Foundation/Foundation.h>
@protocol FlutterBinaryMessenger;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

@class Uint8List;
@class String;

@interface Uint8List : NSObject
@property(nonatomic, strong, nullable) NSNumber * bytesPerElement;
@end

@interface String : NSObject
@end

@protocol HostImageApi
-(nullable Uint8List *)getSystemImageData:(String*)input error:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void HostImageApiSetup(id<FlutterBinaryMessenger> binaryMessenger, id<HostImageApi> _Nullable api);

NS_ASSUME_NONNULL_END
