# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

flutter_application_path = '../t134_map_test_flutter'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

target 'SampleiOSFlutter' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  install_all_flutter_pods(flutter_application_path)

end
