# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
flutter_application_path = 'flutter'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

target 't132_performance_test_ios' do
  install_all_flutter_pods(flutter_application_path)
end
