# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 't132_performance_test_ios' do
  flutter_application_path = 'flutter'
  eval(File.read(File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')), binding)
end
